OScamInfo.py: Fix error in ecm info
Error:
File "/usr/lib/enigma2/python/Screens/OScamInfo.py", line 599, in __init__
    self.loop.start(timeout, False)
TypeError: an integer is required