Remove TwistedLog
1.- By default twisted.log is disabled, if hotplug.socket is disabled, it is not present in tmp, this can cause problems when closing the connection with the STB since systemplugins from hotplug need to find and delete it when closing the Internet connection with the STB.
2.- The only way to get hotplug.socket is to enable twisted.log by default.
But we do not need twisted.log at all, in OpenVision we have a much more powerful and complete debug if we restart enigma2 STB in debug mode ... we will find in /home/root / enigma.xxxxx.debuglog much more complete and accumulative .... with twisted .log we only have a small file and the worst ... if we are in debug mode by ssh or telnet we can no longer follow in real time said debug in the long term.

This is an example of a possible error that we may encounter with this:

<  1119.798> 2019-12-17 22:18:39+0100 [twisted.internet.protocol.Factory] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks

          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks

          File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 441, in _continueFiring

          File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 671, in disconnectAll

        --- <exception caught here> ---
          File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger

          File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext

          File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext

          File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext

          File "/usr/lib/python2.7/site-packages/twisted/internet/unix.py", line 420, in connectionLost

        exceptions.OSError: [Errno 2] No such file or directory: '/tmp/hotplug.socket'